# オブジェクト指向の活用

これまでの課題では触れてきませんでしたが、StandardScalerやLinearRegressionのような クラス と呼ばれるものがPythonなどのプログラム言語では利用できます。


クラスの構文は、オブジェクト指向と呼ばれる考え方を利用したプログラミングの基本的な道具になります。


この課題ではこれまでに既に登場していたクラスを例に、クラスを活用することでどのようなことができるのかを見て学んでいきます。そして課題の後半ではStandardScalerのクラスをスクラッチで自作します。

scikit-learnに用意されている標準化を行うためのクラスStandardScalerを例に見ていきます。サンプルコードを用意しましたので、これを利用しながら理解していきます。


sklearn.preprocessing.StandardScaler — scikit-learn 0.21.3 documentation

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

#### インスタンス化
クラスを使う際はまず以下のようなコードを書きますが、これを インスタンス化 と呼びます。


scaler = StandardScaler()


StandardScalerというクラスオブジェクトから、scalerと名前をつけたインスタンスオブジェクトが作られました。


##### 《クラスの命名法》


Pythonではクラス名は頭文字が大文字、他は小文字という命名法がPEP8により定められています。単語間にアンダースコアは入れません。これを CapWords 方式と呼びます。


はじめに — pep8-ja 1.0 ドキュメント クラスの名前


こういった形式のものはクラスだと判断することができます。


##### 《インスタンスは複数作れる》


あるクラスオブジェクトからは複数のインスタンスオブジェクトを作成することが可能です。


1 scaler0 = StandardScaler()  
2 scaler1 = StandardScaler()  
3 scaler2 = StandardScaler()  

## 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。


Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。


#### メソッド
インスタンス化を行った後には、scaler.fit(X)のような メソッド の実行ができます。StandardScalerのfitメソッドは後でスケーリングに使われる平均と標準偏差を計算する機能があります。


#### インスタンス変数（アトリビュート）
fitメソッドにより平均と標準偏差が計算されましたが、見た目には変化があるわけではありません。しかし、scalerインスタンスの内部では計算結果が保存されています。こういったインスタンスの中で値を保存するものを インスタンス変数 や アトリビュート（属性） と呼びます。ここで平均がscaler.mean_、標準偏差の2乗した値である分散がscaler.var_に保存されています。


以下のようにprint文で出力させることができます。


1 print("平均 : {}".format(scaler.mean_)) # 平均 : [4.86 3.31 1.45 0.22]  
2 print("分散 : {}".format(scaler.var_)) # 分散 : [0.0764 0.0849 0.0105 0.0056]  

#### 《メソッドとインスタンス変数の命名法》


メソッドやインスタンス変数の命名は関数と同様に、すべて小文字で行います。単語をつなぐときにはアンダースコアを入れます。


はじめに — pep8-ja 1.0 ドキュメント メソッド名とインスタンス変数

##### 解答  
Pandas: DataFrame 
matplotlib: ListedColormap  
scikit-learn: LogisticRegression

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください。


##### 《ndarrayやstrもインスタンス》


ドットをつけるというと、NumPyのndarrayに対してndarray.shapeやndarray.sum()のような使い方は何度も利用してきたかと思います。これは、ndarrayもインスタンスオブジェクトであり、shapeはインスタンス変数、sumはメソッドだったということです。


Pythonのコードに登場するデータはどれもインスタンスオブジェクトであり、listやstrもメソッドを持ちます。


（例）


5. データ構造 — Python 3.7.4 ドキュメント 5.1. リスト型についてもう少し


1 l = ['a']  
2 l.append('b') # listのappendメソッド  

4. 組み込み型 — Python 3.7.4 ドキュメント 文字列メソッド


1
2
s = 'Hello, World!'
s.find('W') # strのfindメソッド

#### インスタンス変数をメソッドが利用
最終的に以下のようにして標準化を行います。


X_std = scaler.transform(X)


これはfitメソッドで計算したことでインスタンス変数mean_やvar_に保存されていた値を使い、Xを変換したということです。


このようにクラスには複数のメソッドやインスタンス変数が存在し、これらを組み合わせていろいろな機能を実現します。

#### 解答
メソッド
.append(), .isnull(), .drop(), .dropna() .array(), .range() 

インスタンス
type, display, print, dir, depth

## 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。


今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。


インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。



In [1]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.sum(axis=0) / len(X)
        self.var_ = ((X - self.mean_)**2).sum(axis=0) / len(X) 
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [2]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


どのようなコードになっていたかを確認してみましょう。（問題3に取り組んだ後に見ることを推奨します）スクラッチで作成したものよりも全体的にコードが長いのではないかと思います。inverse_transformメソッドのように作成しなかったものもありますが、それだけではありません。例えば以下のように、warning文が記述されているなどします。



#### 特殊メソッド
ソースコードの中に含まれる、まだ説明していない重要な部分が以下です。


このような__init__というメソッドは、どのクラスにも共通して置かれる コンストラクタ と呼ばれるメソッドです。

今回のスクラッチではcopy、with_mean、with_stdなどのパラメータを省略しましたが、このようにインスタンス化の際にパラメータを指定して保存しておくということはよくある使い方です。


コンストラクタの動作を確認するためのサンプルコードを用意しました。コンストラクタは、インスタンス化が行われる時に自動的に実行されるという働きがあります。こういった特殊な動作をするメソッドを、 特殊メソッド と呼びます。



In [3]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


## 【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。


コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。


クラス名や説明文も適切に書き換えてください。

In [7]:
class ArithmeticOperations():
    def __init__(self, value):
        """
        四則演算を実行するクラス。
        入力されたvalueが数字でない場合は、エラーメッセージを出力

        Parameters
        ----------
        value : float or int  __初期値
        Attributes
        ----------
        value : float or int  __計算結果
        """
        if (type(value)== int or type(value) == float):
            self.value = value
            print("初期値{}が設定されました".format(self.value))
            return
        print("エラー。引数を数字にしてください。")
        print(type(value))
        return
        
        
    def add(self, value2):
        """
        受け取った引数とself.valueの和を取る
        入力されたvalueが数字でない場合は、エラーメッセージを出力

        Parameters
        ----------
        value2 : float or int  __入力値
        Attributes
        ----------
        value : float or int  __計算結果
        """
        if (type(value2)== int or type(value2) == float):
            self.value += value2
            return
        print("エラー。引数を数字にしてください。")
        print(type(value2))
        return
        
    def subtract(self, value3):
        """
        受け取った引数とself.valueの差を取る
        入力されたvalueが数字でない場合は、エラーメッセージを出力

        Parameters
        ----------
        value3 : float or int  __入力値
        Attributes
        ----------
        value : float or int  __計算結果
        """
        if (type(value3)== int or type(value3) == float):
            self.value -= value3
            return
        print("エラー。引数を数字にしてください。")
        print(type(value3))
        return
    
    def multiply(self, value4):
        """
        受け取った引数とself.valueの積を取る
        入力されたvalueが数字でない場合は、エラーメッセージを出力

        Parameters
        ----------
        value4 : float or int  __入力値
        Attributes
        ----------
        value : float or int  __計算結果
        """
        if (type(value4)== int or type(value4) == float):
            self.value *= value4
            return
        print("エラー。引数を数字にしてください。")
        print(type(value4))
        return
            
    def divide(self, value5):
        """
        受け取った引数とself.valueの商を取る
        入力されたvalueが数字でない場合は、エラーメッセージを出力

        Parameters
        ----------
        value5 : float or int  __入力値
        Attributes
        ----------
        value : float or int  __計算結果
        """
        if (type(value5)== int or type(value5) == float):
            self.value /= value5
            return
        print("エラー。引数を数字にしてください。")
        print(type(value5))
        return
        
ari = ArithmeticOperations(5.5)
#if (type(example.value)==int or type(example.value)==float):
print("初期値value : {}".format(ari.value))
ari.add(3)
print("和value : {}".format(ari.value))
ari.subtract(3)
print("差value : {}".format(ari.value))
ari.multiply(3)
print("積value : {}".format(ari.value))
ari.add(3)
print("和value : {}".format(ari.value))
ari.divide(3)
print("商value : {}".format(ari.value))

初期値5.5が設定されました
初期値value : 5.5
和value : 8.5
差value : 5.5
積value : 16.5
和value : 19.5
商value : 6.5


In [1]:
class GinkoKoza():    # 銀行口座クラス(→クラスは"モノ"！)
    def __init__(self, name): 
        self.chokin = 0    # 残高（→インスタンス変数 / Attirbute）
        self.name = name
        print("{}さんの銀行口座を開設しました。".format(name))

    def azukeru(self, money):   #預金メソッド（→メソッドは"処理 / 作業"！）
        self.chokin += money
        self.printfoo()
        print("{}さんの残高: {}".format(self.name, self.chokin))

    def hikiotosu(self, money):
        self.chokin -= money
        print("{}さんの残高: {}".format(self.name, self.chokin))

    def printfoo(self):
        print("foooooo")


nishikori_koza = GinkoKoza("錦織")
jokobitchi_koza = GinkoKoza("ジョコビッチ")

print(nishikori_koza.chokin) # 0

nishikori_koza.azukeru(111)

print(nishikori_koza.chokin) # 111

print(jokobitchi_koza.chokin)

jokobitchi_koza.azukeru(1000000)

錦織さんの銀行口座を開設しました。
ジョコビッチさんの銀行口座を開設しました。
0
foooooo
錦織さんの残高: 111
111
0
foooooo
ジョコビッチさんの残高: 1000000
